apiVersion: v1
kind: Service
metadata:
  name: web-xfusion
spec:
  type: NodePort
  selector:
    # The pod selector uses the pod's name label, so add it to the pod.
    app: xfusion-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
